name: Build Demo Page

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Build Demo Page
      run: yarn build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build